### ISSUE TITLE
Using redux-form decorator makes the saga start after the componentDidMount call

### ISSUE THREAD

**Issue by meikoudras** [keajs/kea-saga#1]
Example Webpackbin [here](https://www.webpackbin.com/bins/-L-alOFADF7pnNE_fTFp)

When using both the redux-form decorator and kea decorator on a component, the component is mounted before the saga starts. When removing the redux-form decorator the saga starts before the component is mounted.

You can reproduce in the example webpackbin by removing the reduxForm decorator and see that the console.log calls switch places.

**Comment by mariusandra** [comment]
If you change the order of the `@reduxForm` and `@kea` decorators, the console messages also switch their order.

I haven't used `reduxForm` for a while, so I'm not sure how much the order matters here. However the situation is that kea starts the saga before the component that it's wrapping has finished mounting. If you have a wrapping `Connect -> Form -> Child`, then Kea can only start before `Form`'s `componentDidMount` runs, which will always after the `Child`'s `componentDidMount`.

I'm not sure how to fix it and if there's anything that needs to be fixed. I hope it all worked out in the end :)

**Comment by meikoudras** [comment]
I would like to keep this issue open and find a solution to this myself. The order matters in the cases where you want kea to provide the initial values to your redux form. So I would really like that it would work both before and after the redux form decorator.

**Comment by mariusandra** [comment]
Still issues with redux-form? :) 
Closing for now.
