### ISSUE TITLE
Kea saga does not include typegen definitions

### ISSUE THREAD

**Issue by rschyboll** [keajs/kea-saga#37]
Hi, i've been working with your library for quite some time now, love it so far. 

In the last week i've wanted to incorporate sagas into my workflow, i did notice though, that kea-saga does not work with kea-typegen. 
In kea-saga [docs](https://keajs.org/docs/plugins/saga#usage), it shows that it is possible to define shared workers for other sagas, but kea-saga does not include those in the type of the logic, so it is not possible to use them with typescript.

I did manage to find a workaround for my use case, but to use the plugin it would be helpful to have it work with kea-typegen. 

I did look into it myself, but in the limited time i could not find a way to make it, seems that my knowledge of the ts compiler api is not good enough, at least for now :D

**Comment by mariusandra** [comment]
Hey, the just released version 3.0.1 has typegen support for `workers` :). Thanks for reporting!

**Comment by rschyboll** [comment]
Awesome, just tested it, seems to be working correctly, thanks!

**Comment by iantbarker** [comment]
I'd like to manually type my logic files and I have typed Kea `Actions` and `Values` but not sure how to type `workers` so `takeLatest` can be typed? Has anyone had success with typing `takeLatest`? 

Currently, when I destructure `this.values` or `this.actions` in a worker, I get error: "Property 'token' does not exist on type 'Saga'"
