### ISSUE TITLE
takeLatest and dynamic logic

### ISSUE THREAD

**Issue by Josh-Love** [keajs/kea-saga#6]
Hey there,

I have a dynamic logic file and I am using takeLatest with sagas. The issue I am having is whenever the same action is fired in two different instances, the saga seems to stop the first action. If I use takeEvery, it works as expected. 

Kea file
`

    import { kea } from 'kea';
    import { put } from 'redux-saga/effects';
    import PropTypes from 'prop-types';

    export default kea({

      key: props => props.id,

      path: key => ['app', 'name', key],

      actions: () => ({
        getSomething: value => ({ value }),
        setSomething: value => ({ value }),
      }),
  
      reducers: ({ actions, key }) => (
        {
          something: [
            '',
            PropTypes.string,
            {
             [actions.setSomething]: (state, payload) => {
                if (key !== payload.key) { return state; }
                return payload.value;
              },
            },
          ],
        }
      ),
  
      // --- Sagas --- \\

      takeLatest: ({ actions, workers }) =>  ({
        [actions.getSomething]: workers.getSomething,
      }),

      workers: {

        * getSomething(action) {
            if (action.payload.key !== this.key) { return; }

            const { setSomething } = this.actions;

            try {
              // Do some kind of promise so your second action runs while the first one is being fulfilled
              yield setTimeout(() => console.log(`${action.payload.key} has fulfilled`), 2000):

              yield put(setSomething(`${action.payload.key} has fulfilled`));
            } catch (err) {
              console.log(err);
            } 
          },

      },
    });
`

Component:
`

    import React from 'react';
    import Logic from './logic';

    @Logic
    class ConnectedLogic extends React.Component {

      componentDidMount() {
        this.actions.getSomething();
      }

      render() {
        return (
          <div>
            Hello
          </div>
        );
      }

    }

    class Parent extends React.Component {

      render() {
        return (
          <div>
           <ConnectedLogic id="1" />
           <ConnectedLogic id="2" />
          </div>
        );
      }
    }

    export default Parent;

`

**Comment by mariusandra** [comment]
Hi, this was an issue in Kea versions before 1.0. Back then all logics with a `key` shared their actions, you just had to make the difference by checking the `key` variable inside the saga. So in this case, takeLatest cancelled what it thought was the right thing. 

This was totally changed in Kea 1.0, after which all logics with an unique key became totally separated.
