### ISSUE TITLE
React Transition Groups Animation overwrites the componentDidMount 

### ISSUE THREAD

**Issue by joshuaRuff** [keajs/kea-saga#9]
Is there a way to programmatically connect actions to sagas? I am wanting to use animations when my component renders but the animation library overwrites the event that would take place in componentDidMount that binds the kea sagas to the actions so when I fire an action the saga never triggers.

Is there a way to rebind the sagas or get around using this issue?

**Comment by mariusandra** [comment]
Hey, since version 1.0, kea and kea-saga no longer overwrite this method.
